version: '3'

services:
  app:
    image: ghcr.io/cherryreptile/weather-bot:latest
    restart: unless-stopped
    environment:
      TG_BOT_TOKEN: ""
      WEBHOOK_URL: ""
      OPENWEATHERMAP_API_KEY: ""
      PORT: "8888"
      DB_NAME: "db"
      DB_USER: "db "
      DB_PASSWORD: "db"
      DB_HOST: "db"
      DB_PORT: "5432"
    ports:
      - "8888:8888"
  db:
    image: postgres:alpine
    restart: unless-stopped
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "db"
    volumes:
      - ./docker/pg/data:/var/lib/postgresql/data
    expose:
      - "5432"